### PR TITLE
Moves background blur from modal to overlay

### PR DESCRIPTION
**Pull request by spencec6**
Moving blurred background from modal's to overlay as mentioned here:
https://discord.com/channels/709210493549674598/735524730328711188/817425329135550506

### CODE REVIEW

**Comment by spencec6** [comment]
Ready for merge. ✅

**Comment by scottrepreneur** [comment]
We can leave the backdrop filter on comingSoonOverlay and proposalActions. those are different than the modals. Looks great @spencec6. Will get this merged then 👍

**Comment by spencec6** [comment]
Ah, good call. Thanks @scottrepreneur!

**Comment by scottrepreneur** [comment]
Accepted over here. Thanks! https://github.com/HausDAO/pokemol-web/pull/868

**Pull request closed without merging**
