### PR TITLE
deploying poster multiple networks

### LINKED ISSUE #1841: MetaPoster: deploy to additional networks
# Deploy Poster contract to supported networks

Poster is deployed on several networks, but not all of the networks DAOhaus supports. Deploy this contract to those networks and note any details necessary for further development. Coordinating with the Poster team on this would be preferred, as they may be able to offer assistance and they can reflect new deploys in their documentation.

### Chains deployed on currently

Contract address `0x000000000000cd17345801aa8147b8D3950260FF` with contracts here: https://github.com/onPoster/contract

- Mainnet Ethereum
- Ropsten
- Rinkeby
- Goerli
- Gnosis Chain

## Deliverables

- [x] Deployed to Kovan
- [ ] Deployed on IDchain
- [x] Deployed on Polygon
- [x] Deployed on Arbitrum
- [x] Deployed on Celo
- [x] Deployed on Optimism

### PR DESCRIPTION
**Pull request by brossetti1**
## GitHub Issue

https://github.com/HausDAO/daohaus-app/issues/1841

## Changes

deploy poster to the following chains:

- [ ] Deployed to Kovan - ignored
- [ ] Deployed on IDchain - ignored
- [x] Deployed on Polygon - https://polygonscan.com/address/0xc59220828774cb373700e7fef92aba4417c6b175#code
- [x] Deployed on Arbitrum - https://arbiscan.io/address/0x10ecbe39b914bdb43850932eb9d505cd0c673321#code
- [X] Deployed on Celo - https://explorer.celo.org/address/0x55fB3D52bF8D2c56cA2159A107aA43e8C16015a1/contracts
- [x] Deployed on Optimism - https://optimistic.etherscan.io/address/0x119e1a9421df2d310a324e04f0ece83278618ddc

## Checks

Before making your PR, please check the following:

- [X] Critical lint errors are resolved
- [X] App runs and builds locally

### CODE REVIEW

**Comment by brossetti1** [comment]
fixes https://github.com/HausDAO/daohaus-app/issues/1841

**Comment by brossetti1** [comment]
only thing i have not done is verify the celo contract - it looks like blockscouts verify endpoint is down.

attaching the correct files for verification:

Poster.sol at https://github.com/onPoster/contract

compiled json file:

```
{
	"language": "Solidity",
	"settings": {
		"optimizer": {
			"enabled": true,
			"runs": 200
		},
		"outputSelection": {
			"*": {
			"": ["ast"],
			"*": ["abi", "metadata", "devdoc", "userdoc", "storageLayout", "evm.legacyAssembly", "evm.bytecode", "evm.deployedBytecode", "evm.methodIdentifiers", "evm.gasEstimates", "evm.assembly"]
			}
		},
		"evmVersion": "byzantium"
	}
}
```

**Comment by plor** [comment]
~Was it not possible to use the deterministic contract address documented in the Poster repo to get the same address across all chains? This is the address advertised by the Poster team, so it would be useful to get that address if possible.~

We aren't doing this, we are ok using our own Poster deploys.

**Comment by brossetti1** [comment]
ah i was just deploying via remix - hmm i can take a look at that -- just grabbed the contract and started deploying, whoops

**Comment by plor** [comment]
Ready to merge, my above comment has be rescinded.

**Pull request merged**
