### PR TITLE
add submission date + fix voting count on prop cards

### PR DESCRIPTION
**Pull request by santteegt**
Solves #1732

### CODE REVIEW

**Comment by skuhlmann** [comment]
@santteegt can you drop some screenshots we can show the design team?

**Comment by santteegt** [comment]
image

**Comment by skuhlmann** [comment]
> image

Looking good.

Finally got design to try something out. Should have a final version soon. Ought to just be a small style adjustment. We might need to check the mobile view as well.

**Comment by skuhlmann** [comment]
@santteegt 

can you access this:
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=3279%3A16259

It's close to what you have, but 
-different style and 
-added some language 'Submitted by'.
- He also moved the view detail button

Screenshot from 2022-03-23 10-38-12

**Comment by santteegt** [comment]
Here's how the proposalCards look based on the latest wireframes

Desktop:

image

Mobile:

image

**Pull request merged**
