### PR TITLE
Feature/lit integration

### LINKED ISSUE #1774: Lit Integration Boost
_**Need some details here**_

Work with the lit team on an integration: daohaus <> lit. Likely dao permissioned google docs.

[existing pr](https://github.com/HausDAO/daohaus-app/compare/feature/lit-boost?expand=1)

this boost can be modeled similar to the snapshot boost - potentially showing a link to `Drive Links` on the main Dao page which would link to the LitBoost page where all the google drive doc links can be displayed.

Integration scope: 
* On boosts page, a "Share Google Drive Item" button that takes them to our Google Drive dashboard, with some stuff prefilled from URL variables
* On boosts page, a list of the Google Drive files that were shared by anyone in the DAO

Data to send to Lit as URL variables when the user clicks on the "Share Google Drive Item" button:
* Contract Address
* Contract Type (molochdao v2.1)
* DAO Name

Functionality of boost:
1.  Boost is added to dao
2. User can sign up to google lit oauth
3. Which unlocks a table of shareable links for the entire dao to access 

fetching shareable links (Lit Docs):

1) simply check if the user is a member of a dao: https://developer.litprotocol.com/docs/AccessControlConditions/evmBasicExamples#must-be-a-member-of-a-dao-molochdaov21-also-supports-daohaus
2) more advanced options where you can check the number of shares a user has in a DAO or anything the members() function returns: https://developer.litprotocol.com/docs/AccessControlConditions/evmCustomContractCalls#must-have-at-least-1-share-in-a-given-molochdaov21-dao

relavent resources:

https://github.com/LIT-Protocol/lit-oauth/tree/main/server - backend service of the Lit protocol - navigate to google for relavent backend service for this story.

https://gist.github.com/glitch003/76ac07a95cd11ddc1571254f59682665 - gist for interacting with Lit
https://github.com/LIT-Protocol/lit-oauth/blob/main/server/oauth/google.js#L398-L407 -  To get all shares from a DAO
https://github.com/LIT-Protocol/lit-oauth/blob/main/server/oauth/google.js#L225-L237 -  create a share of a google drive file

supported `LIT_CHAINS` - https://github.com/LIT-Protocol/lit-js-sdk/blob/main/src/lib/constants.js#L30

### PR DESCRIPTION
**Pull request by brossetti1**
## GitHub Issue

https://github.com/HausDAO/daohaus-app/issues/1774

## Changes

- [X] adding install Lit Boost with proper descriptions
- [X] building custom components for Lit integration

adding initial communication with lit protocol:

- [X] sign wallet and pass auth to lit for document interaction
- [X] get shared documents from dao - currently no documents will return because we need to wait for upgrades on Lits server
- [X] receiving response from getAllShares (get all documents) and (getAllDaoShares)

## Packages Added

- lit-protocol-sdk - sdk used for querying and interacting with Lit Protocol
- path - this one is odd, I was getting a weird error around webpack 5 and manually installing node polyfills - adding path fixed this (has something to do with `libsodium` a dependency from lit-protocol-sdk) - see [Details for info](#lit-sdk-errorrs)

## Checks

Before making your PR, please check the following:

- [X] Critical lint errors are resolved
- [X] App runs and builds locally

## Details

#lit-sdk-errorrs

solved by including `path` in the `package.json`
```
ERROR in ./node_modules/libsodium/dist/modules/libsodium.js 39:23-46
Module not found: Error: Can't resolve 'path' in '/Users/brianrossetti/Projects/current/web3/projects/hausDAO-top/daohaus-app/node_modules/libsodium/dist/modules'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
```

## Follow ups
There are a few interactions with Lit which are causing unintended consequences:

- Lit seems to only allow one account to be connected to an

### CODE REVIEW

**Comment by brossetti1** [comment]
I still need to add a decent amount of stuff, getting a draft open in case anyone feels like they want to leave comments.

TODO: 
- UI is janky and needs to be resorted
- [X] - build cards to display the document data that is returned.
- [ ] - lit is forcing a redirect to ethereum mainnet when redirecting to their oauth UI - might need to communicate with their team to discuss this.
- [x] auth-sigs are stored in localstorage, therefore, if a user swithes wallets - things break. Working on namespacing auth sigs by wallet address

for reference - here is the ui flow that is acting oddly:
https://www.loom.com/share/60eaa153dc9c44a28f74123bc61b282a
DAOhaus - 11 June 2022 - Watch Video

**Review by alexkeating — APPROVED** [review]

**Comment by plor** [comment]
Should we merge this in and not expose it until the lit team fixes their services? Not sure how long we want this branch hanging out.

**Comment by brossetti1** [comment]
@plor its should be fine to hang out - Chris at Lit is responding on the issues, hes just busy in between so his responses dont get to me for a few days.

the majority of work left is on Lit's side, they should get back to us over the weekend, thats when Chris is usually sending a response.

**Comment by alexkeating** [comment]
I think we should get this in behind a flag while Lit implements on their side

**Comment by brossetti1** [comment]
@plor added a feature flag for checking `REACT_APP_DEV` for this one. if all is good, feel free to merge it.

just an fyi - fetching google docs is hooked up to `getDAOShares` which is currently unresponsive on Lits side. Until they make the changes, you will not see the docs that have been shared at the moment. If you DO wnat to see the docs, you can change the endpoint to `/getAllShares` on the following line:

https://github.com/HausDAO/daohaus-app/blob/b3da1d76c24ab4970bc76e17a5f02d3aee86f7e7/src/pages/LitProtocolGoogle.jsx#L64

**Comment by plor** [comment]
Cool, I'll add a task to the backlog to remove this when we're notified that Lit has made these changes. We can then circle back and decide to remove the flag.

**Comment by brossetti1** [comment]
@plor caught this one up with develop, should be good to go

**Comment by brossetti1** [comment]
fixes [#1774](https://github.com/HausDAO/daohaus-app/issues/1774)

**Pull request merged**
